version: "3.9"
services:
  web:
    container_name: "find-movies"
    build:
      context: .
      dockerfile: "Dockerfile"
    environment: 
      PORT: 3000
    ports:
      - "3001:3000"
    command: sh -c "yarn build && yarn start"
    volumes:
      - ./:/app
      - /app/node_modules